name: Update all Trusted Lists

on:
  schedule:
    - cron:  '25 3 * * *'

jobs:
  download:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download all Trusted Lists
      run: |
        python gpk.py download-all
    - name: Push the updated files to GitHub
      run: |
        git config user.email "hesus.ruiz@gmail.com"
        git config user.name "Jesus Ruiz"
        git add .
        git commit -m 'Update Trusted Lists'
        git push origin main
